### ISSUE TITLE
https://github.com/krakjoe/phpdbg

### ISSUE THREAD

**Issue by digitalkaoz** [jami/xdebug-cli#3]
why not builtin phpdbg?

**Comment by jami** [comment]
I think phpdbg is kindof orphaned. Also there is a lack of support and documentation. XDebug is so simple and i want to play around with dbgp. Actually, that should not be a debugger at all. But a tracer and profiler. Sometimes you just wander off

**Comment by jami** [comment]
@digitalkaoz  but you are right phpdbg is an alternative

**Comment by digitalkaoz** [comment]
I just wanted to troll a bit ;) nice that you wrote it in Go :)

Jan Michalowsky <notifications@github.com> schrieb am Do., 31. Mai 2018,
01:56:
